SELECT DBMS_STATS.GET_PARAM('ESTIMATE_PERCENT') FROM dual;
SELECT DBMS_STATS.GET_PARAM('DEGREE') FROM dual;
SELECT DBMS_STATS.GET_PARAM('CASCADE') FROM dual;
SELECT DBMS_STATS.GET_PARAM('NO_INVALIDATE') FROM dual;
SELECT DBMS_STATS.GET_PARAM('GRANULARITY') FROM dual;
SELECT DBMS_STATS.GET_PARAM('METHOD_OPT') FROM dual;
SELECT DBMS_STATS.GET_PARAM('STALE_PERCENT') FROM dual;
SELECT DBMS_STATS.GET_PARAM('PUBLISH') FROM dual;
SELECT DBMS_STATS.GET_PARAM('AUTOSTATS_TARGET') FROM dual;
SELECT DBMS_STATS.GET_STATS_HISTORY_RETENTION FROM dual;

EXEC DBMS_STATS.GATHER_SCHEMA_STATS('&schema_name');